version: '3.8'

services:
  db:
    image: postgres:16
    container_name: VK-container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
    ports:
      - "3333:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: